adobe/aio-lib-cloudmanager

README.md, src/helpers.js, src/index.js, src/sdktypes.jsdoc.js, tools/generate-jsdoc-types.js, types.d.ts
Export `getCurrentStep` and `getWaitingStep`
#3
Needed to finish refactoring of plugin
n/a
=> export getCurrentStep. fixes #3

package.json
get latest changes from aio-lib-core-logging
@justinedelson I am carrying this change over all libraries (and the template library)
=> trivial: fix aio-lib-core-logging caret

README.md, src/index.js, src/sdktypes.jsdoc.js, src/types.jsdoc.js, tools/generate-jsdoc-types.js, types.d.ts
Corrected name of options object
#6
Confusing documentation
Just docs
=> correct name of ListPipelineOptions. fixes #6

src/sdktypes.jsdoc.js, types.d.ts
Update generated types to reflect inclusion of environmentId in PipelineExecutionStepState
#15
Brings generated types up to date
Manual testing
=> add environment id. fixes #15

src/constants.js, src/index.js, test/environments.test.js, test/jest/jest.fetch.setup.js, test/pipelines.test.js, test/programs.test.js
Makes problem type handling default to some reasonable behavior (with various edge cases handled) and provide a mechanism for future problem name URIs to be registered to customize the handling if necessary.
#17 
* Unit Tests
* Manual Testing
=> improve handling of undefined problem types. fixes #17

package.json, src/index.js
Remove a bunch of duplicated code
#19
less duplication is good ;)
* Unit Test
=> remove duplicated finding code. fixes #19

e2e/e2e.js, src/index.js
Some minor eslint issues which block updating eslint-plugin-jest and eslint-config-standard.
See
https://github.com/adobe/aio-lib-cloudmanager/pull/26
https://github.com/adobe/aio-lib-cloudmanager/pull/27
=> chore: addressing eslint issues

.github/workflows/ci.yml, .github/workflows/release.yml, tools/generate-jsdoc-types.js
Update jsdoc generation script to be compatible with js-yaml v4
Also add doc generation to github workflows to catch similar issues in the future
#43
* Manual Testing
* CI
=> fix(build): correct jsdoc generation to work with js-yaml v4. fixes #43

src/index.js, test/jest/jest.fetch.setup.js, test/programs.test.js
Catch exceptions when parsing error response bodies
#53
Resulted in UnhandledPromiseRejectionWarnings and strange behavior in I/O Runtime
Unit tests
Manual testing
=> fix(auth): some response bodies were not correctly handled. fixes #53

package.json, types.d.ts
Not sure why handlebars is here... Looks like a copy/paste error during the initial extraction
=> chore(deps): remove handlebars

src/index.js, test/jest/jest.fetch.setup.js, test/pipelines.test.js
Handle case where problem.errors is an object, not an array.
#96
Validation issues are swallowed
* Unit tests
* Manual tests
=> fix(variables): output variables validation issues in error message. Fixes #96

package.json
=> chore(deps): update fetch-mock to 9.11.0

.eslintrc.json, .vscode/settings.json, eslint_rules/aio-lib-cloudmanager-error-codes.js, package.json
Add an eslint rule that validates that errors are handling property
#114 
#116 
#117
These errors should be caught earlier.
Tested WIP on those PRs... waited to submit until open issues were fixed
=> chore(lint): add custom rule to check error code usage

package.json, renovate.json
=> chore(deps): revert change to eslint jsdoc

src/index.js
Reduce complexity in this method
#168
Clean code
Unit tests
=> fix(debt): reduce complexity in createIpAllowList. fixes #168

src/SDKErrors.js, src/index.js, test/executions.test.js, test/jest/data/execution1003.json, test/jest/data/execution1017.json, test/jest/data/execution1018.json, test/jest/jest.fetch.setup.js, test/log-tail.test.js
Add a new `tailExecutionStepLog` method
#170 
See https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/377
Unit tests
=> feat(execution): add tailExecutionStepLog method. fixes #170

.eslintrc.json, src/index.js
Also add eslint rule to ensure this doesn't happen again
#172 
It's ugly
eslint
=> fix: remove console.log statement from tailExecutionStepLog. fixes #172

README.md, src/SDKErrors.js, src/constants.js, src/index.js, test/commerce.test.js, test/jest/jest.fetch.setup.js
Added postCommerceCLICommand
* added postCommerceCLICommand
* added unit tests
* updated documentation
#177 
Adds Commerce functionality to cli
Unit tests
=> Added postCommerceCLICommand. Fixes #177

src/SDKErrors.js, src/constants.js, src/index.js, test/jest/jest.fetch.setup.js, test/pipelines.test.js
Add a new pipeline invalidate cache method
#204
New API function
Unit tests
Manual tests
=> feat(pipeline): add invalidatePipelineCache support. fixes #204

README.md, src/index.js, test/jest/jest.fetch.setup.js
Added getCommerceCLICommand
- Updated call for Commerce cloudmanager CLI
- updated unit tests to include coverage for updated GET commerce CLI call
- Updated documentation to include newly updated GET commerce CLI call
#208 
Expands Adobe Commerce functionality to the CLI
Unit tests
=> feat(commerce): update getCommerceCLICommand. fixes #208

src/index.js, test/commerce-log-tail.test.js, test/jest/jest.fetch.setup.js
I created an alternate pipeBody function, that accepts an additional argument, a transform function. 
*  an alternate pipeBody function, that accepts an additional argument, a transform function
* a  _commerceLogTransform function to pass to the new pipeBodyWithTransform function
* calling  pipeBodyWithTransform inside the commerce tail logs function instead of pipeBody
* updated unit tests
* manual and unit testing
=> feat(commerce): improved log format #227

src/index.js, test/commerce.test.js, test/jest/jest.fetch.setup.js
Changed which endpoint the POST commerce cammand executions hits
*Changed endpoint for POST
*Updated unit tests
unit (cannot manual test since change has not been implemented on back end yet)
=> feat(commerce): endpoint fixes #302

.github/workflows/release.yml
Release job gets blocked in pending status.
#379
=> fix(release): Update release job to ubuntu-latest. Fixes #379

.github/workflows/ci.yml, package.json
=> chore!: set minimal node ver 17

.github/workflows/npm-publish.yml, .github/workflows/release.yml
=> chore: set release node to 17
